version: '3.4'

services:
  yourprojecttracker:
    image: yourprojecttracker
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
    command: python main.py
