version: '3.4'

services:
  yourprojecttracker:
    image: ghcr.io/liudmilalv/your_project_tracker:latest
    env_file:
      - ./.env
    volumes:
      - ./db/:/app/website/db/
    ports:
      - 5000:5000
